### ISSUE TITLE
Upgrade to support Phoenix 1.3 phx structure

### ISSUE THREAD

**Issue by smpallen99** [noma4i/sublime-phoenix-beagle#2]
Do you have any plans for an update? If not, I might take it on when I have some time.

**Comment by noma4i** [comment]
All you need just to update paths in `https://github.com/noma4i/sublime-phoenix-beagle/blob/master/PhoenixBeagle.sublime-settings` I will do this in master and leave old one in a branch.

**Comment by smpallen99** [comment]
Yes, that's what I did. I'll share my changes with you. Feel free to use it or toss it. 

Just as an FYI, I also enhanced my SublimeREPL to add `iex mix` and `iex mix phoenix` options.

Oops, responded to the wrong issue. I have not looked at the phoenix 1.3 stuff. Sorry for the confusion.
